### ISSUE TITLE
defect: scripts/export.sh modifies API Definitions

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-demo#218]
Step 1: Create a new API
Step 2: run `scripts/export.sh`
Step 3: run git status

![Screenshot 2023-10-04 at 15 03 03](https://github.com/TykTechnologies/tyk-demo/assets/1465130/e5c3640f-bbf2-44d4-aa84-c8905d13d62e)

Step 4: run git diff on the changed files

4 API definitions are affected:

2 API Definitions, the issue appears to be a non-idempotent API ID.

![Screenshot 2023-10-04 at 15 08 52](https://github.com/TykTechnologies/tyk-demo/assets/1465130/aebdc4fc-b8eb-4647-a15e-f07ff0771d62)

2 API Definitions, the issue appears to be the order of fields in the analytics_plugin object

![Screenshot 2023-10-04 at 15 08 13](https://github.com/TykTechnologies/tyk-demo/assets/1465130/00357e74-289d-4d97-b983-499580358e39)

**Comment by davegarvey** [comment]
The issue with the webhook ids is due to their random nature. They can't be controlled, so change every time the API is imported, so will show as modifications when you export. You can either commit the change or revert, either is fine and makes no difference to the functionality.

For the field ordering, I'm not sure what's causing it, but it's likely outside of the export script's control. Like the webhook issue, I think it's fine to either commit or revert.
